In [ ]:
def lemma_me(sent):
    sentence_tokens = nltk.word_tokenize(sent.lower())
    pos_tags = nltk.pos_tag(sentence_tokens)

    sentence_lemmas = []
    for token, pos_tag in zip(sentence_tokens, pos_tags):
        if pos_tag[1][0].lower() in ['n', 'v', 'a', 'r']:
            lemma = lemmatizer.lemmatize(token, pos_tag[1][0].lower())
            sentence_lemmas.append(lemma)
    
    return sentence_lemmas

        
x1 = lemma_me('the brown fox jumped over Neo and Nala')
x2 = lemma_me('Vegetables are types of plants.')
x3 = lemma_me('A vegetable is a kind of plant')
x2_1 = lemma_me('A vegetable is a type of plant')
print(x1, x2, x2_1, x3)

In [12]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt')

text = 'Originally, vegetables were collected from the wild by hunter-gatherers. Vegetables are all plants. Vegetables can be eaten either raw or cooked.'
question = 'What are vegetables?'

def lemma_me(sent):
    sentence_tokens = nltk.word_tokenize(sent.lower())
    pos_tags = nltk.pos_tag(sentence_tokens)

    sentence_lemmas = []
    for token, pos_tag in zip(sentence_tokens, pos_tags):
        if pos_tag[1][0].lower() in ['n', 'v', 'a', 'r']:
            lemma = lemmatizer.lemmatize(token, pos_tag[1][0].lower())
            sentence_lemmas.append(lemma)
    
    return sentence_lemmas

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/rodneyfinkel/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/rodneyfinkel/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rodneyfinkel/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [13]:
sentence_tokens = nltk.sent_tokenize(text)
sentence_tokens.append(question)
sentence_tokens

['Originally, vegetables were collected from the wild by hunter-gatherers.',
 'Vegetables are all plants.',
 'Vegetables can be eaten either raw or cooked.',
 'What are vegetables?']

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(tokenizer=lemma_me)
tf = tv.fit_transform(sentence_tokens)
tf2 = tf.toarray()
tf2

array([[0.27717414, 0.53114624, 0.        , 0.        , 0.53114624,
        0.53114624, 0.        , 0.27717414],
       [0.41988018, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.8046125 , 0.41988018],
       [0.32713399, 0.        , 0.62688384, 0.62688384, 0.        ,
        0.        , 0.        , 0.32713399],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678]])

In [15]:
import pandas
df = pandas.DataFrame(tf2, columns=tv.get_feature_names())
df

be   collect      cook       eat  hunter-gatherer  originally  \
0  0.277174  0.531146  0.000000  0.000000         0.531146    0.531146   
1  0.419880  0.000000  0.000000  0.000000         0.000000    0.000000   
2  0.327134  0.000000  0.626884  0.626884         0.000000    0.000000   
3  0.707107  0.000000  0.000000  0.000000         0.000000    0.000000   

      plant  vegetable  
0  0.000000   0.277174  
1  0.804612   0.419880  
2  0.000000   0.327134  
3  0.000000   0.707107

In [16]:
from sklearn.metrics.pairwise  import cosine_similarity
values = cosine_similarity(tf[-1], tf)
values

array([[0.39198343, 0.59380024, 0.46263733, 1.        ]])

In [17]:
index = values.argsort()[0][-2]

values_flat = values.flatten()
values_flat.sort()
values_flat

array([0.39198343, 0.46263733, 0.59380024, 1.        ])

In [18]:
coeff = values_flat[-2]
coeff

0.593800244493221

In [19]:
if coeff > 0.3:
    print(sentence_tokens[index])
    

Vegetables are all plants.
